---
- hosts: us_host
  pre_tasks:
      - name: update apt cache if needed.
        become: yes
        become_method: sudo
        apt: update_cache=yes cache_valid_time=3600
  tasks:
      - name: 安装用于管理apt源工具
        become: yes
        become_method: sudo
        apt: name={{item}} state=present
        with_items:
            - python-apt
            - python-pycurl
      - name: "Download zabbix-release_3.4"
        become: yes
        become_method: sudo
        get_url:
           url: "https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb"
           dest: /tmp/zabbix-release_3.4-1+xenial_all.deb
           mode: 0755
      - name: install zabbix-release
          become: yes
          become_method: sudo
          shell: >
            dpkg -i /tmp/zabbix-release_3.4-1+xenial_all.deb
      - name: install zabbix-agent
                become: yes
                become_method: sudo
                apt: name={{item}} state=present update_cache=yes
                with_items:
                - zabbix-agent

