---
- name: Remove "zabbix*" package
  become: yes
  become_method: sudo
  yum:
    name: zabbix-*
    state: absent
- name: "Download zabbix-release_4 and install AmazonOS"
  become: yes
  become_method: sudo
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
    state: present
  #  get_url:
  #     url: "https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb"
  #     dest: /tmp/zabbix-release_3.4-1+xenial_all.deb
  #     mode: 0755
  # - name: install zabbix-release
  # - become: yes
  # - become_method: sudo
  # - shell: >
  # -       dpkg -i /tmp/zabbix-release_3.4-1+xenial_all.deb
- name: ensure a list of packages installed zabbix-agent
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - zabbix-agent
- name: backup zabbixoldconfig
  become: yes
  become_method: sudo
  shell: >
     mv /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf.bak
- name: copy templates to dest
  become: yes
  become_method: sudo
  copy:
    src: ./templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0744
    force: yes
  notify: start zabbix-agent